import cv2
import numpy as np
img=cv2.imread('image_1.png')
print(img.shape)
blank_image = np.ones(img.shape[:2],np.uint8)*255
cv2.imshow('blank',blank_image)
print(blank_image.shape)
cv2.waitKey(0)
img=cv2.medianBlur(img,5)
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
circles=cv2.HoughCircles(gray,cv2.HOUGH_GRADIENT,1,180,param1=80,param2=30,minRadius=200,maxRadius=400)
circles=np.uint16(np.around(circles))
for (x,y,r) in circles[0,:]:
    cv2.circle(blank_image,(x,y),r,(0,0,0),50)
cv2.imshow("main",blank_image)
cv2.waitKey(0)
blank=cv2.bitwise_not(blank_image)
cv2.imshow('blank',blank)
hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
lower_white=np.array([0,0,0],dtype=np.uint8)
upper_white=np.array([0,0,255],dtype=np.uint8)
mask_img=cv2.inRange(hsv,lower_white,upper_white)
print(mask_img.shape)
cv2.imshow('edited',mask_img)
cv2.waitKey(0)
result=cv2.bitwise_and(blank,blank,mask=mask_img)
result=cv2.bitwise_not(result)
cv2.imshow('result',result)
cv2.waitKey(0)
cv2.destroyAllWindows()